version: "2"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: metabase_postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  metabase:
    image: metabase/metabase:v0.41.5
    container_name: metabase_app
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: $POSTGRES_USER
      MB_DB_PASS: $POSTGRES_PASSWORD
      MB_DB_HOST: postgres
      MB_ENCRYPTION_SECRET_KEY: $MB_ENCRYPTION_SECRET_KEY
  datadog:
    image: "datadog/agent:latest"
    environment:
      DD_API_KEY: $DD_API_KEY
      DD_LOGS_ENABLED: 'true'
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: 'true'
      DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE: 'true'
      DD_SITE: datadoghq.eu
      DD_CONTAINER_EXCLUDE: name:datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  nginx:
    image: nginx:1.21
    restart: "unless-stopped"
    volumes:
      - ./nginx/metabase.conf:/etc/nginx/conf.d/metabase.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 80:80
      - 443:443

volumes:
  postgres: