version: "2"
services:
  postgres:
    image: postgres:9.6.19-alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  metabase:
    image: metabase/metabase:v0.41.4
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: $POSTGRES_USER
      MB_DB_PASS: $POSTGRES_PASSWORD
      MB_DB_HOST: postgres
    ports:
      - "3000:3000"
volumes:
  postgres:
